esbullington/react-d3

- src/barchart.js
Refs https://github.com/esbullington/react-d3/issues/19
> Render axes on componentDidMount

- tests/areachart-tests.js
- tests/barchart-tests.js
- tests/linechart-tests.js
- tests/piechart-tests.js
Just remove some unused code in tests
> remove unused code in tests

- dist/public/js/main.js
- docs/examples/main.js
- src/index.js
- src/scatterchart.jsx
- tests/index.js
- tests/scatterchart-tests.js
Adds scatter chart. Basically almost same with multi line chart.
> Scatter chart

- src/scatterchart.jsx
- tests/scatterchart-tests.js
Please note that instead of setting `color` as state, I add another state `strokeWidth` to help animating. Also I use `shouldComponentUpdate` to decide if they should do the animation. Feel free to correct me if you think there is another better way ( or you prefer your approach stated in #28 ). I din't any test for the animation since we don't have test spies. If you think adding test for animation is necessary, I will try to add them by adding dependency like `sinon.js`. 
If you're cool with this kind of approach, I will add animation for other charts on this branch too. :bar_chart: :chart_with_upwards_trend:
> Add hover animation

- src/common/voronoi.jsx
- src/scatterchart.jsx
- tests/scatterchart-tests.js
Thanks @esbullington for factor out `voronoi.jsx`. This cleans up a lot.
> Clean up voronoi.jsx and make scatter chart's test pass

- README.md
Adds explicit examples of how to use the namespace requires for the lib. Why? Because I had to dive into the code to ensure I was using the right naming convention and I would find it quicker and easier to use with explicit README examples
`README.md`
Ensure the `markdown` is valid format and styled appropriately
Thanks for making the lib
> Update README with explicit namespace naming examples

- src/utils/index.js
What do you think of this? This is backwards-compatible with current code and handles multiple dimensions.
It's also more resilient if either `xAccessor` or `yAccessor` isn't defined.
> Utils upgrade to work with any number of dimensions

- src/treemap.jsx
These two props were not getting passed down to the Cell component.
> Pass fontSize and textColor props down to Cell.

- package.json
This seems to fix the dependencies so I can just do "npm install && npm run build" and it all works.
> adding react-tools to make it easier to build

- src/areachart/AreaChart.jsx
- src/barchart/BarChart.jsx
- src/candlestick/CandlestickChart.jsx
- src/common/axes/Label.jsx
- src/common/axes/XAxis.jsx
- src/common/axes/YAxis.jsx
- src/common/charts/LegendChart.jsx
- src/linechart/Circle.jsx
- src/linechart/DataSeries.jsx
- src/linechart/Line.jsx
- src/linechart/LineChart.jsx
- src/piechart/Arc.jsx
- src/piechart/DataSeries.jsx
- src/piechart/PieChart.jsx
Browse through all code base because din't catch up with so many changes. So just did this.
> Improve code (following guideline and use es6 features that are supported)

- src/common/axes/AxisLine.jsx
- src/common/axes/AxisTicks.jsx
- src/common/axes/XAxis.jsx
- src/common/axes/YAxis.jsx
added propTypes and tickStroke to AxisTicks
consolidated xScale and yScale into scale prop
corrected tick placement for all orients
> added tickStroke for AxisTicks and cleaned up AxisTicks

- src/areachart/AreaChart.jsx
Hey @esbullington,
Here is the pull request for issue #167
JP
> Fix for AreaChart stacking issues #167

- src/common/axes/AxisTicks.jsx
- src/common/charts/LegendChart.jsx
- src/piechart/Arc.jsx
- src/scatterchart/DataSeries.jsx
- src/scatterchart/ScatterChart.jsx
- src/scatterchart/VoronoiCircle.jsx
- src/scatterchart/VoronoiCircleContainer.jsx
Quick fix for react key warning and run some lint.
> Fix arc key warning

- src/piechart/ArcContainer.jsx
- src/piechart/PieChart.jsx
Reason: hoverAnimation prop is missing from top component.
> Fix piechart not animated problem

- docs/examples/main.js
- src/areachart/AreaChart.jsx
- src/candlestick/CandlestickChart.jsx
- src/common/Legend.jsx
- src/common/charts/BasicChart.jsx
- src/common/charts/Chart.jsx
- src/common/charts/LegendChart.jsx
- src/linechart/LineChart.jsx
- src/mixins/CartesianChartPropsMixin.js
- src/mixins/ViewBoxMixin.js
- src/mixins/index.js
- src/scatterchart/ScatterChart.jsx
@samdalton 
Added a commit to fix React warning.
* CSS inline style - for example `vertical-align` -> `verticalAlign`
* usage of `React.PropTypes.oneOf` and `React.PropTypes.oneOfType“
> About life viewbox object

- src/common/charts/LegendChart.jsx
> Add d3 dependency to LegendChart.jsx

- gulpfile.js
- package.json
> Use babelify for es6 and jsx transformation

- package.json
Could we add this lines to package.json as a temporary solution until somebody has time to solve the problem as suggested by @yang-wei:
> One way to solve this is to compiled all code(babel, jsx) from src into directory. Then ts user can use our module straight from there.
> Fix problem with typescript caused by #741de83

- src/common/axes/XAxis.jsx
- src/linechart/LineChart.jsx
Pass xAxisStrokeWidth and yAxisStrokeWidth to being able to set the width of the line axis of line charts.
> Set axis line width of line charts

- docs/examples/main.js
The code above uses {{ but the example docs are not
> fix viewBoxObject in the example

- README.md
> Update demo page in link and add es6 example

- package.json
> Removed missing `npm run build` script
