esbullington/react-d3

src/areachart.jsx
src/barchart.jsx
src/linechart.jsx

This change preserves the linechart's behavior for data consisting of only positive values – the axes will still start at 0.  But for data with negative values, the axis will begin at the lowest negative value (see x-axis of image below).  What do you think?
I'm happy to add a test, but since the axes are not rendered by React, the ticks aren't found by the TestUtils methods.

Allow axes to go negative

---

src/common/axes.jsx

Need to selectAll on xAxisClassSelect (as you are doing for the YAxis). This selection only updates the first instance of xAxis but fails if you have multiples of the same chart type on a page.

Fixes bug with xAsisClassSelect

---

README.md

The old demo link in the README is pointing to a page with out of date instructions. Changing the link to point to a more current demo page.

updating the demo link

---

gulpfile.js
package.json

- Stopped build crashing on browserify errors, which is really annoying when watching
- Added chalk for log colors

Gulp improvements

---

src/piechart/Arc.jsx

Hi
I noticed this small syntax error that stopped gulp from doing it's thing, and also broke the tests.
Cheers
Graham

Fixed syntax error in piechart/arc.jsx that broke the build

---

package.json

Browserifying a project that depends on react-d3 from a local checkout (via `npm link`) currently fails with parse errors due to the jsx/es6 syntax in source files. This PR adds a [transform](https://github.com/substack/browserify-handbook#browserifytransform-field) field to package.json, which makes browserify transpile the source code on the fly in cases like this.
This is super useful for debugging purposes and should cause no additional overhead when react-d3 is installed from npm, as a different package.json is shipped with the npm release.

Add browserify transform field to package.json

---

src/areachart/DataSeries.jsx

Use index instead of name in line with convention so that the legend corresponds to the chart.

Conforms area chart to use index instead of name for selecting color

---

src/areachart/AreaChart.jsx
src/areachart/DataSeries.jsx
src/linechart/LineChart.jsx

I've implemented the the same interface to control interpolation as currently implemented in `LineChart` (using the `interpolate` and `interpolationType` props).
I also added some missing propTypes to `LineChart`.

Add interpolation to area chart

---

src/piechart/Arc.jsx
src/piechart/DataSeries.jsx
src/piechart/PieChart.jsx
tests/piechart-tests.js

I want to have a custom legend for the PieChart, and don't want to show inner labels for a small chart (< 50px) where the text labels will not fit. The best option I saw was to allow disabling of the inner and outer labels via props to PieChart: `showInnerLabels` and `showOuterLabels`. Let me know if you had other thoughts on this or it doesn't look right.

Adds showInnerLabel and showOuterLabel props to PieChart

---

docs/examples/main.js
src/piechart/Arc.jsx
src/piechart/DataSeries.jsx
src/piechart/PieChart.jsx

Passing in a `stroke` prop that is a string color (e.g. "white") to PieChart will render a white border around each segment, producing a chart like:

Added stroke support to PieChart to enable lines between

---

src/common/charts/BasicChart.jsx
src/common/charts/LegendChart.jsx
tests/basicchart-tests.js
tests/index.js
tests/legendchart-tests.js

I need charts to render without a title and currently even if you don't pass in a `title` prop, an `h4` element is rendered. This changes `BasicChart` and `LegendChart` to not render any unnecessary elements.

Optional chart titles

---

src/linechart/DataSeries.jsx
src/linechart/Line.jsx

Fixed a bug in the linechart/DataSeries component where the render method was polling the first value of the data array to check for the x-axis data type, without first checking to see if the element of the data array was defined. A check has been placed into DataSeries's render() to check the length of the array first, returning null if it is empty. Note that this check does not cover sparse arrays, which will still potentially cause the render to fail.
I also added a PropType for seriesName in DataSeries and added a default value for it since it is required by portions of the code, such as creating an id. I also removed the PropType for data from linechart/Line since the data prop is not used by Line, and, it was the wrong type anyways.

Bug fix in linechart/DataSeries

---

src/scatterchart/DataSeries.jsx
src/scatterchart/ScatterChart.jsx
src/scatterchart/VoronoiCircleContainer.jsx
src/utils/index.js
tests/scatterchart-tests.js

This was my mistake. In scatter chart, all circles are rendered with same color. Color should differ if they are not from the same series. 
Added another property `seriesName` to the objects of allValues in `utils/index.js`. Added a test for this to prevent future mistake.
Also I realised that in those graphs that we are using d3 color palettes, users don't really have a option to color their graph. They can only opt for another 3 color palettes that d3 provided. Might open another issue regarding this if you want a further discussion.

Scatterchart series color

---

src/linechart/Circle.jsx
src/linechart/Line.jsx

Fixes a bug that caused the `linechart/Line` and `linechart/Circle` to not update their colors when their `props.fill` property changed if the component was already mounted. This is because `getInitialState` is only called the fist time the component is mounted, not every time it is rendered. Especially since we use non-random keys, most of the time the components are re-used instead of destroyed (unmounted) and recreated (mounted).

Fixes a bug that causes linechart/Line and linechart/Circle to not update their color properly

---

src/barchart/BarChart.jsx
src/barchart/DataSeries.jsx

Modified `barchart/BarChart` and `barchart/Dataseries` to support the `props.colors` and `props.colorAccessor` functions.
Also passed missing properties into the containing `Chart`.
Note: this is not a breaking change. Users who currently pass the `fill` property to `barchart/BarChart` can still do so, though it will be ignored.

Added props.colors and props.colorAccessor support to BarChart

---

src/common/Legend.jsx
src/common/axes/Label.jsx
src/common/axes/XAxis.jsx
src/common/axes/YAxis.jsx
src/common/charts/BasicChart.jsx
src/common/charts/Chart.jsx
src/common/charts/LegendChart.jsx
src/mixins/CartesianChartPropsMixin.js
tests/areachart-tests.js
tests/legend-tests.js
tests/linechart-tests.js

This stems from #225 , but it goes a bit farther, but also doesn't do everything the OP in #225 wanted.
1. This adds a `className` to every chart component. `className` is only exposed to the parent of the component - it would be too ugly right now to expose all the class names on the top-level chart, and, the names are unique enough that they should make due for basically all users; I will document the names at some point.
2. **Important: breaking change**: as part of going through all the Chart props, I also went through and **removed supporting `data` being an object - it MUST be an array now**. I think this change is worth it. It makes the code a lot simpler, and allows us to not have to do gimmicky checks and casts which may or may not work. If the user can't figure out that they …

Changes and additions to Chart components

---

src/scatterchart/DataSeries.jsx
src/scatterchart/ScatterChart.jsx
src/scatterchart/VoronoiCircle.jsx
src/scatterchart/VoronoiCircleContainer.jsx
src/utils/index.js
tests/scatterchart-tests.js

This pr does some major refactoring to the `ScatterChart` code.
1. Fixes missing props, `propTypes`, and `getDefaultProps`
2. Fixes the bug where animation was making the component fail to respond to changes due to missing `componentWillReceiveProps`
3. Fixes non-standard calls to `colorAccessor`
4. Because data for `ScatterChart` goes through `utils.flattenData`, that method had to be modified to ensure that each record still retained all original data, and that each record knew from which series it came from.
5. `utils.flattenData` had a small potential bug fixed, replacing `in` with `hasOwnProperty`
6. Code across `ScatterChart` has been simplified
7. Based on #227 , support for `data` as an Object has been removed
8. "Magic constants" have been moved into `defaultProps`
9. Tests have …

Refactoring of ScatterChart code + minor changes to utils.flattenData

---

docs/examples/main.js
src/linechart/DataSeries.jsx
src/linechart/Line.jsx

I took this approach to adding `stroke-width` and `stroke-dasharray` props to LineChart. It is different from how we specify colors with a `colorAccessor` prop but seemed vastly simpler.

Exposed stroke-width and added stroke-dasharray support to line chart

---

src/utils/index.js

In utils.shade, if the values of red, green, or blue are single-digit, the resulting string may not be a proper hex string. Single digits need to be prepended with '0'.

fixes toString bug with single-digit RGB values in utils.shade

---

gulpfile.js
karma.conf.js

Running gulp test each time is slow. So prefer to run it continuously.

Add gulp task - tdd to run test continuously

---

src/linechart/LineChart.jsx

Pass property `interpolationType` from `LineChart` to `DataSeries` to actually being able to use it.

InterpolationType for LineChart

---

src/common/charts/BasicChart.jsx
src/common/charts/LegendChart.jsx

Although I didn't set a title for the chart, there was the h4 `rd3-chart-title`
element in my DOM. In my case `this.props.title = ""` if I don't set a title.
However, this is not the case for phantom.js. Does that depend on the
browser version? I'm using Chrome and Firefox. Anyway, with the changes I
don't have the title element and the karma tests end successfully.

Bugfix: Don't add h4 title element to chart if there is no title

---

src/linechart/DataSeries.jsx

This param did not make it into VoronoiCircleContainer so setting this param was totally useless. But I fixed it.

param hoverAnimation fixed

---

.editorconfig
src/areachart/AreaChart.jsx
src/barchart/BarChart.jsx
src/candlestick/CandlestickChart.jsx
src/common/axes/AxisTicks.jsx
src/common/axes/Label.jsx
src/common/axes/XAxis.jsx
src/common/axes/YAxis.jsx
src/linechart/LineChart.jsx
src/mixins/CartesianChartPropsMixin.js
src/mixins/DefaultAccessorsMixin.js
src/mixins/ViewBoxMixin.js
src/mixins/index.js
src/scatterchart/ScatterChart.jsx
tests/barchart-tests.js
tests/candlestick-tests.js
tests/piechart-tests.js
tests/scatterchart-tests.js
tests/treemap-tests.js
tests/utils/datagen.js

Some description of the implementation here: https://github.com/esbullington/react-d3/commit/abdd34fa00bc652b37b4be720ac99523c481c555
Feedback welcome.
There are no tests, I suppose it wouldn't be hard to test the rotation and translation behavior of axis and tick labels, but at least this is open to review now.
**In the images below, the less-than-ideal axis label placements and the candlestick bottom axis overlap issue are due to the fact that these screenshots are of the example page with no properties modified other than horizontal={true}.**  When adjusting `margins` and (for candlestick) `yAxisOffset` to better values for horizontal charts, they look better.  To implement two different default margins depending on orientation would be additional work.

Horizontal cartesian charts

---

docs/examples/main.js

There were a couple typos in the documentation for the area chart that cause the graph not to render. A misspelling of height and an object that was missing the extra set of {}.

Fix typos in documentation

---

package.json

Without phantomjs in the package.json, I found that running `npm test` led to an error about missing phtanomjs package.

Added phantomjs to package.json to allow npm test after npm install
